#! /bin/sh

CKSCA="$XDG_CACHE_HOME/conky-pywal-scheme"

SELclr(){
	case $1 in
		"dim"|"bright"|"normal")
			CLBRI="$1"
			CLNUM="$2" ;;
		*)
			CLBRI=$(shuf -e dim bright normal -n1)
			CLNUM="$1" ;;
	esac
	[ "$CLNUM" -ge "0" ] 2> /dev/null && [ "$CLNUM" -le "15" ] 2> /dev/null \
		&& cat $CKSCA/$CLBRI/color$CLNUM \
		|| cat $CKSCA/$CLBRI/color$(shuf -i 1-15 -n1)
}

PNThelp(){
	printf '%s\n' \
        '| $1 = --help	-h = "Show Help"						       |'\
        '| $1 = ""	   = "grabs color code for conky, any feild left blank is randomized"  |'\
        '	\  opions:								       |'\
	'	 | $1 	= 	"normal" "dim" "bright" 	= "color brightness"	       |'\
	'	 | $1,$2=	1,2,3,...13,14,15		= "Pywal/Terminal color value" |'\
	'	 |'\
	'	 | The cpws-rlist command has all the same options as cpws-gc.'\
	'	 | Accept only runs when text is being piped in , then it randomized color of each line'\
	'	 | Do not use cok-py-sh-rlist without piping somehing into it though. Its really slow if you dont.'
}

case $1 in
	"--help"|"-h")
		PNThelp ;;
	*)
		SELclr $@
esac
