#! /bin/sh

CKSCA="$XDG_CACHE_HOME/conky-pywal-scheme"

SELclr(){
	case $1 in
		"dim"|"bright"|"normal")
			CLBRI="$1"
			shift ;;
		*)
			CLBRI=$(shuf -e dim bright normal -n1)
	esac
	[ -n "$1" ] \
		&& cat $CKSCA/$CLBRI/color$(shuf "$@" -n1) \
		|| cat $CKSCA/$CLBRI/color$(shuf -i 0-15 -n1)
}

PNThelp(){
	printf '%s\n' \
        '| $1 = --help	-h = "Show Help"						       |'\
        '| $1 = ""	   = "grabs color code for conky, any feild left blank is randomized"  |'\
        '	\  opions:								       |'\
	'	 | $1 	= 	"normal" "dim" "bright" 	= "color brightness"	       |'\
	'	 | $@   = this uses the shuf command, in a range 1-15 type man shuf in the treminal for more details= "Pywal/Terminal color value" |'\
	'	 |'\
	'	 | The cpws-rlist command has all the same options as cpws-gc.'\
	'	 | Accept only runs when text is being piped in , then it randomized color of each line'\
	'	 | Do not use cok-py-sh-rlist without piping somehing into it though. Its really slow if you dont.'
}

case $1 in
	"--help"|"-h")
		PNThelp ;;
	*)
		SELclr $@
esac
